name: Daily Commit

on:
  schedule:
    - cron: '17 4 * * *'  # Runs daily at 04:17 UTC (adjust if needed)
  workflow_dispatch:  # optional: allow manual runs too

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make daily commit by 23f1002151@ds.study.iitm.ac.in
        run: |
          echo "Daily heartbeat: $(date)" >> daily-log.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add daily-log.txt
          git commit -m "Daily commit from GitHub Action"
          git push
